/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_hotkey
#define _Included_hotkey
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_hotkey_startloop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
